language: php

php:
  - 5.5
  - 5.6
  - 7
  - nightly
  - hhvm

## Run on container environment
sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

env:
  - PACKAGES='symfony/browser-kit=2.7.*'
  - PACKAGES='symfony/browser-kit=2.8.*'
  - PACKAGES='symfony/browser-kit=3.2.*'
  - PACKAGES='symfony/browser-kit=3.3.*'
  - PACKAGES='symfony/browser-kit=~3.4@dev'

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: PACKAGES='symfony/browser-kit=2.7.*' deps='low'
    - php: 7.1
      env: PACKAGES='symfony/symfony=~4.0@dev' deps='no'
    - php: nightly
      env: PACKAGES='symfony/symfony=~4.0@dev' deps='no'

  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - composer require --no-update ${PACKAGES}
  - if [ "$deps" = "no" ] || [ -z "$deps" ]; then composer --prefer-source install; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-source --prefer-lowest --prefer-stable update; composer --prefer-source install; fi;

script:
  - mkdir -p build
  - vendor/bin/phpunit --colors -c phpunit.xml
